sudo: required
language: node_js
node_js:
    - "0.12"

services:
    - docker

before_install:
    - docker build -f Dockerfile -t dev .
    - docker tag dev:latest $DOCKER_SERVER/dev:latest

after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS -e none $DOCKER_SERVER
    - docker push $DOCKER_SERVER/dev:latest
