sudo: required
language: node_js
node_js:
    - "0.12"

services:
    - docker

before_install:
    - docker build -f Dockerfile -t dev .

after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS -e none $DOCKER_SERVER
    - docker push dev
