sudo: required
language: node_js
node_js:
  - "0.12"

services:
  - docker

before_install:
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - pip install --user awsebcli # install eb cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --region us-east-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker build -f Dockerfile -t deploy_test:$TRAVIS_BRANCH .

after_success:
  - chmod +x ./deploy.sh && ./deploy.sh

# whitelist
branches:
  only:
    - master
