sudo: required
language: node_js
node_js:
    - "0.12"

services:
    - docker

before_install:
    - docker build -f Dockerfile -t soramusoka/travis .

after_success:
    - docker login -e $DOCKER_EMAIL -p $DOCKER_PASS -u $DOCKER_USER
    - docker push soramusoka/travis
