branch-defaults:
  default:
    environment: apple
  master:
    environment: apple
deploy:
  artifact: "release.zip"
global:
  application_name: docker-test
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1
  default_region: us-east-1
  profile: null
  sc: git
